In [3]:
import pandas as pd
import os
import openpyxl

In [4]:
os.listdir()

['.ipynb_checkpoints',
 'practica1.ipynb',
 'reviews.csv',
 'reviews.ipynb',
 'supermarkets',
 'Untitled.ipynb']

In [5]:
df1 = pd.read_csv('./supermarkets/supermarkets.csv')
df1

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [6]:
df2 = pd.read_json('./supermarkets/supermarkets.json')
df2

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [7]:
df3 = pd.read_excel('./supermarkets/supermarkets.xlsx',sheet_name=0)
df3

,ID,Address,City,State,Country,Supermarket Name,Number of Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [8]:
df4 = pd.read_csv('./supermarkets/supermarkets.csv')
df4

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [9]:
df5 = pd.read_csv('./supermarkets/supermarkets-semi-colons.txt', sep=';')
df5

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [10]:
df6 = pd.read_csv('./supermarkets/supermarkets-without-headers.txt', sep=';', header=None)
df6

   0                1              2                 3    4             5   6
0  1     3666 21st St  San Francisco          CA 94114  USA       Madeira   8
1  2   735 Dolores St  San Francisco          CA 94119  USA   Bready Shop  15
2  3      332 Hill St  San Francisco  California 94114  USA   Super River  25
3  4     3995 23rd St  San Francisco          CA 94114  USA    Ben's Shop  10
4  5  1056 Sanchez St  San Francisco        California  USA       Sanchez  12
5  6  551 Alvarado St  San Francisco          CA 94114  USA    Richvalley  20

In [11]:
df6.columns = ['ID','Direccion','Ciudad','Estado','Pais','Nombre','Empleados']
df6

,ID,Direccion,Ciudad,Estado,Pais,Nombre,Empleados
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [12]:
# el cambio no es permanente
df6.set_index('ID')

,Direccion,Ciudad,Estado,Pais,Nombre,Empleados
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [13]:
df6

,ID,Direccion,Ciudad,Estado,Pais,Nombre,Empleados
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [14]:
# crea una nuevo dataframe
df7 = df6.set_index('ID')
df7

,Direccion,Ciudad,Estado,Pais,Nombre,Empleados
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [15]:
# para aplicar el cambio permanenente
df6.set_index('ID', inplace=True)
df6

,Direccion,Ciudad,Estado,Pais,Nombre,Empleados
ID,,,,,,
1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
3,332 Hill St,San Francisco,California 94114,USA,Super River,25
4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [16]:
df6.set_index("Direccion", inplace=True)
df6

                        Ciudad            Estado Pais        Nombre  Empleados
Direccion
3666 21st St     San Francisco          CA 94114  USA       Madeira          8
735 Dolores St   San Francisco          CA 94119  USA   Bready Shop         15
332 Hill St      San Francisco  California 94114  USA   Super River         25
3995 23rd St     San Francisco          CA 94114  USA    Ben's Shop         10
1056 Sanchez St  San Francisco        California  USA       Sanchez         12
551 Alvarado St  San Francisco          CA 94114  USA    Richvalley         20

In [17]:
df6.set_index("Direccion", inplace=True)
df6

KeyError: "None of ['Direccion'] are in the columns"

In [21]:
df5.loc["735 Dolores St":"332 Hill St"]

Empty DataFrame
Columns: [ID, Address, City, State, Country, Name, Employees]
Index: []

In [22]:
df5

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [24]:
# Capturar datos 
df5.iloc[1:4,1:4]

          Address           City             State
1  735 Dolores St  San Francisco          CA 94119
2     332 Hill St  San Francisco  California 94114
3    3995 23rd St  San Francisco          CA 94114

In [29]:
# Eliminacion de columna
df5.drop('City',axis=1)

   ID          Address             State Country          Name  Employees
0   1     3666 21st St          CA 94114     USA       Madeira          8
1   2   735 Dolores St          CA 94119     USA   Bready Shop         15
2   3      332 Hill St  California 94114     USA   Super River         25
3   4     3995 23rd St          CA 94114     USA    Ben's Shop         10
4   5  1056 Sanchez St        California     USA       Sanchez         12
5   6  551 Alvarado St          CA 94114     USA    Richvalley         20

In [35]:
# Eliminacion de fila
df5.drop(1,axis=0)

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [40]:
df6.index

Index(['3666 21st St', '735 Dolores St', '332 Hill St', '3995 23rd St',
       '1056 Sanchez St', '551 Alvarado St'],
      dtype='object', name='Direccion')

In [41]:
df6.columns

Index(['Ciudad', 'Estado', 'Pais', 'Nombre', 'Empleados'], dtype='object')

In [43]:
df6

                        Ciudad            Estado Pais        Nombre  Empleados
Direccion
3666 21st St     San Francisco          CA 94114  USA       Madeira          8
735 Dolores St   San Francisco          CA 94119  USA   Bready Shop         15
332 Hill St      San Francisco  California 94114  USA   Super River         25
3995 23rd St     San Francisco          CA 94114  USA    Ben's Shop         10
1056 Sanchez St  San Francisco        California  USA       Sanchez         12
551 Alvarado St  San Francisco          CA 94114  USA    Richvalley         20

In [42]:
# Elimina filas basado en las coordenadas del indice
df6.drop(df6.index[0:3],axis=0)

                        Ciudad      Estado Pais      Nombre  Empleados
Direccion
3995 23rd St     San Francisco    CA 94114  USA  Ben's Shop         10
1056 Sanchez St  San Francisco  California  USA     Sanchez         12
551 Alvarado St  San Francisco    CA 94114  USA  Richvalley         20

In [47]:
len(df1)

6

In [50]:
df1['Continenent'] = df1.shape[0]*['North America']
df1

,ID,Address,City,State,Country,Name,Employees,Continenent
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8,North America
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15,North America
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25,North America
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10,North America
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12,North America
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20,North America

In [52]:
# Cantidad de filas y columnas
df1.shape

(6, 8)

In [54]:
df1["Continent"] = df1["Country"] + ',' + 'North America'
df1

,ID,Address,City,State,Country,Name,Employees,Continenent,Continent
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8,North America,"USA,North America"
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15,North America,"USA,North America"
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25,North America,"USA,North America"
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10,North America,"USA,North America"
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12,North America,"USA,North America"
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20,North America,"USA,North America"

In [56]:
# Elimino la columna con nombre erroneo con el parametro inplace se sobreescribe el df original
df1.drop('Continenent', axis=1,inplace=True)

In [57]:
# Creo una nueva columna tomando como parametro los datos de otra
df1["Continent"] = df1["Country"] + ',' + 'North America'
df1

,ID,Address,City,State,Country,Name,Employees,Continent
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8,"USA,North America"
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15,"USA,North America"
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25,"USA,North America"
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10,"USA,North America"
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12,"USA,North America"
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20,"USA,North America"

In [58]:
from geopy.geocoders import ArcGIS
nom = ArcGIS()

In [59]:
nom.geocode("3995 23rd St, San Francisco CA94114")

Location(3995 23rd St, San Francisco, California, 94114, (37.752926991206, -122.431710000351, 0.0))

In [60]:
import pandas
df = pandas.read_csv('./supermarkets/supermarkets.csv')
df

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [63]:
df['Address'] = df['Address']+","+df["City"] + "," + df["State"] + "," + df["Country"]
df

,ID,Address,City,State,Country,Name,Employees
0,1,"3666 21st St,San Francisco,CA 94114,USA,San Fr...",San Francisco,CA 94114,USA,Madeira,8
1,2,"735 Dolores St,San Francisco,CA 94119,USA,San ...",San Francisco,CA 94119,USA,Bready Shop,15
2,3,"332 Hill St,San Francisco,California 94114,USA...",San Francisco,California 94114,USA,Super River,25
3,4,"3995 23rd St,San Francisco,CA 94114,USA,San Fr...",San Francisco,CA 94114,USA,Ben's Shop,10
4,5,"1056 Sanchez St,San Francisco,California,USA,S...",San Francisco,California,USA,Sanchez,12
5,6,"551 Alvarado St,San Francisco,CA 94114,USA,San...",San Francisco,CA 94114,USA,Richvalley,20

In [64]:
df["Coordinates"] = df["Address"].apply(nom.geocode)

In [71]:
columna = df.iloc[:,7]
columna

0    (3666 21st St, San Francisco, California, 9411...
1    (735 Dolores St, San Francisco, California, 94...
2    (332 Hill St, San Francisco, California, 94114...
3    (3995 23rd St, San Francisco, California, 9411...
4    (1056 Sanchez St, San Francisco, California, 9...
5    (551 Alvarado St, San Francisco, California, 9...
Name: Coordinates, dtype: object

In [77]:
df['Latitude'] = df['Coordinates'].apply(lambda x: x.latitude if x != None else None)
df['Longitude'] = df['Coordinates'].apply(lambda x: x.longitude if x != None else None)
df

,ID,Address,City,State,Country,Name,Employees,Coordinates,Latitude,Longitude
0,1,"3666 21st St,San Francisco,CA 94114,USA,San Fr...",San Francisco,CA 94114,USA,Madeira,8,"(3666 21st St, San Francisco, California, 9411...",37.756635,-122.429419
1,2,"735 Dolores St,San Francisco,CA 94119,USA,San ...",San Francisco,CA 94119,USA,Bready Shop,15,"(735 Dolores St, San Francisco, California, 94...",37.757831,-122.425374
2,3,"332 Hill St,San Francisco,California 94114,USA...",San Francisco,California 94114,USA,Super River,25,"(332 Hill St, San Francisco, California, 94114...",37.755849,-122.428812
3,4,"3995 23rd St,San Francisco,CA 94114,USA,San Fr...",San Francisco,CA 94114,USA,Ben's Shop,10,"(3995 23rd St, San Francisco, California, 9411...",37.752927,-122.431710
4,5,"1056 Sanchez St,San Francisco,California,USA,S...",San Francisco,California,USA,Sanchez,12,"(1056 Sanchez St, San Francisco, California, 9...",37.752156,-122.429962
5,6,"551 Alvarado St,San Francisco,CA 94114,USA,San...",San Francisco,CA 94114,USA,Richvalley,20,"(551 Alvarado St, San Francisco, California, 9...",37.753592,-122.433253

In [76]:
# Tipo de dato de una celda
type(df.at[0,"Coordinates"])

geopy.location.Location