## 1. Overview of the dataframe

In [26]:
import pandas as pd
from datetime import datetime
from pytz import utc
data = pd.read_csv("reviews.csv", parse_dates = ['Timestamp'])

In [12]:
data.head()

,Course Name,Timestamp,Rating,Comment
0,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 06:25:52+00:00,4.0,NaN
1,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 05:12:34+00:00,4.0,NaN
2,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 05:11:03+00:00,4.0,NaN
3,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 03:33:24+00:00,5.0,NaN
4,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 03:31:49+00:00,4.5,NaN

In [13]:
data.shape

(45000, 4)

In [14]:
data.columns

Index(['Course Name', 'Timestamp', 'Rating', 'Comment'], dtype='object')

In [15]:
data.hist('Rating')

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

## 2. Selecting data from dataframe

### Select column

In [16]:
data ['Rating'].mean()

np.float64(4.442155555555556)

### Select multiple columns

In [17]:
data[['Course Name', 'Rating']]

                                             Course Name  Rating
0      The Python Mega Course: Build 10 Real World Ap...     4.0
1      The Python Mega Course: Build 10 Real World Ap...     4.0
2      The Python Mega Course: Build 10 Real World Ap...     4.0
3      The Python Mega Course: Build 10 Real World Ap...     5.0
4      The Python Mega Course: Build 10 Real World Ap...     4.5
...                                                  ...     ...
44995                 Python for Beginners with Examples     4.0
44996  The Python Mega Course: Build 10 Real World Ap...     5.0
44997  The Python Mega Course: Build 10 Real World Ap...     5.0
44998                 Python for Beginners with Examples     5.0
44999  The Python Mega Course: Build 10 Real World Ap...     5.0

[45000 rows x 2 columns]

### Selecting a row

In [18]:
data.iloc[3]

Course Name    The Python Mega Course: Build 10 Real World Ap...
Timestamp                              2021-04-02 03:33:24+00:00
Rating                                                       5.0
Comment                                                      NaN
Name: 3, dtype: object

### Selecting multiple rows

In [19]:
data.iloc[1:3]

,Course Name,Timestamp,Rating,Comment
1,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 05:12:34+00:00,4.0,NaN
2,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 05:11:03+00:00,4.0,NaN

### Selecting a section

In [20]:
data[['Course Name','Rating']].iloc[1:3]

                                         Course Name  Rating
1  The Python Mega Course: Build 10 Real World Ap...     4.0
2  The Python Mega Course: Build 10 Real World Ap...     4.0

### Selecting a cell

In [21]:
data['Timestamp'].iloc[2]

Timestamp('2021-04-02 05:11:03+0000', tz='UTC')

In [22]:
data.at[2,'Rating']

np.float64(4.0)

## 3. Filtering data based on conditions

### One condition

In [23]:
d= data[data['Rating'] > 4]
d['Rating'].mean()

np.float64(4.87316015861281)

### Multiple conditions

In [24]:
data[(data['Rating'] > 4) & (data['Course Name'] == 'The Complete Python Course: Build 10 Professional OOP Apps')]['Rating']

31      5.0
34      5.0
43      5.0
45      5.0
101     4.5
       ...
2501    4.5
2502    5.0
2509    5.0
2523    5.0
2525    5.0
Name: Rating, Length: 351, dtype: float64

## 4. Time-based filtering

In [28]:
data[(data['Timestamp'] >= datetime(2020,7,1, tzinfo=utc) ) & (data['Timestamp'] <= datetime(2020,12,31, tzinfo=utc))]

,Course Name,Timestamp,Rating,Comment
3065,Interactive Data Visualization with Python and...,2020-12-30 23:28:34+00:00,3.0,NaN
3066,The Python Mega Course: Build 10 Real World Ap...,2020-12-30 22:59:02+00:00,4.0,NaN
3067,The Python Mega Course: Build 10 Real World Ap...,2020-12-30 22:40:10+00:00,4.5,NaN
3068,The Python Mega Course: Build 10 Real World Ap...,2020-12-30 21:56:41+00:00,4.5,NaN
3069,The Python Mega Course: Build 10 Real World Ap...,2020-12-30 21:14:34+00:00,4.5,NaN
...,...,...,...,...
9729,The Python Mega Course: Build 10 Real World Ap...,2020-07-01 03:09:44+00:00,3.5,NaN
9730,The Python Mega Course: Build 10 Real World Ap...,2020-07-01 03:09:12+00:00,5.0,NaN
9731,The Python Mega Course: Build 10 Real World Ap...,2020-07-01 02:40:58+00:00,4.0,NaN
9732,The Python Mega Course: Build 10 Real World Ap...,2020-07-01 02:04:02+00:00,5.0,nice
9733,The Python Mega Course: Build 10 Real World Ap...,2020-07-01 00:01:34+00:00,2.0,Hard to follow if u have no experience program...

### 5. From data to information

#### Average rating

In [29]:
data['Rating'].mean()

np.float64(4.442155555555556)

#### Average rating for a particular course

In [31]:
data[data['Course Name'] == 'The Python Mega Course: Build 10 Real World Applications']['Rating'].mean()

np.float64(4.477270180942244)

#### Average rating for particular period

In [37]:
data[(data['Timestamp'] >= datetime(2020,1,1, tzinfo=utc) ) & 
(data['Timestamp'] <= datetime(2020,12,31, tzinfo=utc))]['Rating'].mean()

np.float64(4.476541271662339)

#### Average rating for a particular period for a particular course

In [38]:
data[(data['Timestamp'] >= datetime(2020,1,1, tzinfo=utc) ) & 
(data['Timestamp'] <= datetime(2020,12,31, tzinfo=utc)) &
(data['Course Name'] == 'The Python Mega Course: Build 10 Real World Applications')
]['Rating'].mean()

np.float64(4.506076089208037)

#### Average of uncommented raings

In [42]:
data[data['Comment'].isnull()]['Rating'].mean()
# lo contrario seria notnulll

np.float64(4.433679746603492)

#### Average commented ratings

In [43]:
data[data['Comment'].notnull()]['Rating'].mean()

np.float64(4.489777908515959)

#### Number of uncommented ratings

In [46]:
data[data['Comment'].isnull()]['Rating'].count()

np.int64(38201)

#### Number of commented ratings

In [47]:
data[data['Comment'].notnull()]['Rating'].count()

np.int64(6799)

#### Number of comments containing a certain word

In [50]:
data[data['Comment'].str.contains('accent',na=False)]['Rating'].count()

np.int64(77)

#### Average of commented ratings with "accent" in comment

In [51]:
data[data['Comment'].str.contains('accent',na=False)]['Rating'].mean()

np.float64(3.8636363636363638)